### ISSUE TITLE
No question 9_6 in the CSV, but 9_5 and 9_7.

### ISSUE THREAD

**Issue by plogacev** [hpiwowar/jdap#1]
In JDAP 2.csv, there are questions 9_5 and 9_7, but no question 9_6. Is this expected?

**Comment by hpiwowar** [comment]
I double-checked, and yes this is expected.  Long answer:  What happened was that I deleted the subquestion 9_6 after typing in the questions to Qualtrics, and replaced with another sub-question using the Qualtrics UI, which is called 9_17.  Short answer:  it is no problem.
