### ISSUE TITLE
Authors without papers with archived data in journals after JDAP introduction.

### ISSUE THREAD

**Issue by plogacev** [hpiwowar/jdap#10]
Almost 20% of respondents in the 'After JDAP' category has given this response. This seems a bit suspicious.

**Comment by hpiwowar** [comment]
Makin sure I understand --  so 20% of authors who publish in a journal after it has implemented JDAP say they do not have any papers that don't have any archived data?  As in -- they are claiming that all of their papers have archived data, is that right?   How different is this than the percentage of authors who claim this after publishing in the journals 'before JDAP'?

**Comment by plogacev** [comment]
Sorry, it should have been 'Authors without papers _with_ archived data'. That is, 20% of authors who  publish in a journal after it has implemented JDAP say they do not have any papers that _have_ archived data. This suggests that our JDAP adoption dates might be off.

**Comment by hpiwowar** [comment]
Nah, I think this is very plausible.  Many journals don't strictly enforce policies, especially data archiving policies.  In my previous research I've found journals with mandated data archiving often have many papers without archived data.  

It's a great fact to call out in our results though!
