### ISSUE TITLE
Difference between blank fields and dots?

### ISSUE THREAD

**Issue by plogacev** [hpiwowar/jdap#2]
Is there a difference between blank fields and dots? For example in question Q18_9, first two rows?
I assume that both should be treated as missing, but is there a difference?

**Comment by hpiwowar** [comment]
Good question.  The difference is whether they got to that page in the survey.  If they abandoned the questionnaire before that question was displayed, the data is a blank field -- nothing was recorded at all.  If they saw the question (and perhaps submitted questions to some of the other sub-questions on the same page) the non-answer of that subquestion was recorded as a dot.  

I think we can treat them the same for analysis.
