### ISSUE TITLE
Contradictory responses 

### ISSUE THREAD

**Issue by plogacev** [hpiwowar/jdap#3]
Regarding the following question (question 11 in the CSV):
"To your knowledge, what are the policies of these stakeholders as they apply to online public archiving of the datasets associated with your (month) (year) publication in (journal)? Choose all that apply."
- Why is selection of multiple options admissible regarding each stackeholder? The options seem exclusive to me.
- 45 out of 4114 records regarding the journal contain multiple responses. It is not quite clear how to deal with such records. 
  -> Some participants answered "Recommends online public archiving" and "Requires online public archiving". If they meant that both are true, we should subsume it under "requires". But if they meant that one _or_ the other are true, it is basically equivalent to "I don't know". 
  -> Furthermore, there are instances of participants replying "Recommends online public archiving", "Requires online public archiving", _and_ "No policy"/"I don't know". 
  -> My guess is that all responses containing "I don't know" should be treated as if only "I don't know" had been selected, and all contradictory responses ("requires" and "no policy") should be treated as either missing, or as "I don't know". What do you think?

**Comment by hpiwowar** [comment]
Yeah, I think you are right, they should have been exclusive.  I'm not sure what I was thinking making them "choose all that apply".  Darn!  My mistake.  Sorry it is causing problems now.

Yeah, great suggestions on how to deal with multiple responses.  Here's my thoughts based on them:
- subsume "recommends and requires" as "requires"
- all responses containing "I don't know" should be treated as if only "I don't know" had been selected
- all contradictory responses ("requires" and "no policy") should be treated as missing.  (though if you feel strongly that "I don't know" is the better call here, I can be convinced)

That covers all the bases?
