### ISSUE TITLE
Very few responses in the second half of 2013

### ISSUE THREAD

**Issue by plogacev** [hpiwowar/jdap#6]
Why are there so few responses from the second half of 2013? There are only 11 in the third quarter, 0 in the fourth quarter. In contrast, there are 433 responses in the second quarter of 2013, and 622 in the first quarter of 2014.

**Comment by hpiwowar** [comment]
I think this is because I didn't send out many invitations in the second half of 2013, and caught up by sending several months late, in the first quarter of 2014.
