### ISSUE TITLE
The columns journal, month, and year.

### ISSUE THREAD

**Issue by plogacev** [hpiwowar/jdap#7]
Can you confirm that the columns journal, month, and year are values that participants provided in response to the question regarding their 'most recent publication'?

**Comment by hpiwowar** [comment]
The columns journal, month, and year were actually provided by me -- custom values were coded into the URL that I generated when I created the custom invitation email to each author.  

I used Web of Science to get a dump of all corresponding authors for each issue of each journal, and then sent each of the corresponding authors a custom email that included the journal/month/year for their paper encoded in the URL (and also mentioned in full text in the email).  The survey software got the values through the URL, and then the survey software included them in the output data columns with the survey results and also used them to populate the questions 9 and 10 before it showed them to the survey takers:

"To your knowledge, what are the policies of these stakeholders as they apply to online public archiving of the datasets associated with your (month) (year) publication in (journal)? "
and 
"Are all datasets associated with your (month) (year) publication in (journal) publicly available online?"
