### ISSUE TITLE
JDAP adoption dates

### ISSUE THREAD

**Issue by plogacev** [hpiwowar/jdap#8]
I just checked in the updated table regarding JDAP adoption dates. Where the adoption dates were not listed on the journal homepage, I used archive.org to approximate the date. In some cases, the adoption dates seem to be different from the ones in the original table (according to the archive.org snapshorts of the publication guidelines). In many cases, all I could get was a range.
It looks like the JDAP adoption dates for our sample of journals vary quite widely. For now, I am using the later date in the range as the adoption date, but this is clearly a bit too imprecise. I suppose we might have to ask the journals directly.
Can you take a look at the new table and tell me whether this is something we can work with?

**Comment by hpiwowar** [comment]
Yup, it looks great.  Nice work @plogacev !
