### ISSUE TITLE
Invitations

### ISSUE THREAD

**Issue by plogacev** [hpiwowar/jdap#9]
Do we have data on the exact numbers of invitations? Ideally including the publication date for each invitation.

**Comment by hpiwowar** [comment]
Yup!  I just uploaded this file, which contains this information, one row per initial survey invitation (reminders were sent separately, about a week later).  They are broken down by journal, but I didn't start keeping track of that column till after the first few months alas.  https://github.com/hpiwowar/jdap/blob/master/data/sent_initial_anonymous.csv
